<#
  Scans the /Data folder and regenerates assets/js/data-manifest.js so every
  page's freshness banner can compare its "last reviewed" date against the
  actual files sitting in /Data.

  Run this after adding, replacing, or removing any file under /Data.
  It does NOT read the content of your files or contact the internet —
  it only records file names and their last-modified timestamps.
#>

$root = Split-Path -Parent $PSScriptRoot
$dataDir = Join-Path $root "Data"
$outFile = Join-Path $root "assets\js\data-manifest.js"

if (-not (Test-Path $dataDir)) {
    Write-Error "Data folder not found at $dataDir"
    exit 1
}

$files = Get-ChildItem -Path $dataDir -Recurse -File | ForEach-Object {
    $rel = $_.FullName.Substring($dataDir.Length + 1).Replace('\', '/')
    $parts = $rel -split '/'
    # category = top-level folder, or top-level/second-level for DIPN/<topic>
    if ($parts.Length -gt 2 -and $parts[0] -eq 'DIPN') {
        $category = "$($parts[0])/$($parts[1])"
    } else {
        $category = $parts[0]
    }
    [PSCustomObject]@{
        category = $category
        name     = $_.Name
        path     = "Data/$rel"
        modified = $_.LastWriteTime.ToString("yyyy-MM-ddTHH:mm:ss")
        sizeKB   = [math]::Round($_.Length / 1KB, 1)
    }
}

$generatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
$json = @{
    generatedAt = $generatedAt
    files       = $files
} | ConvertTo-Json -Depth 4

$jsContent = "/* AUTO-GENERATED by scripts/update-manifest.ps1 on $generatedAt — do not hand-edit. */`nwindow.DATA_MANIFEST = $json;`n"
Set-Content -Path $outFile -Value $jsContent -Encoding UTF8

Write-Host ""
Write-Host "Manifest regenerated: $($files.Count) file(s) found under /Data" -ForegroundColor Green
$files | Group-Object category | ForEach-Object {
    Write-Host ("  {0,-28} {1} file(s)" -f $_.Name, $_.Count)
}
Write-Host ""
Write-Host "Reload any open study hub page in your browser to see updated freshness status."
